name: Lint
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Build
    env:
      NODE_ENV: development
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
